 
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
 
jobs:

	configure_infrastructure: 
		docker:
			- image: python:3.7-alpine3.11
		steps:
			- checkout
			- add_ssh_keys:
					fingerprints: ["49:de:32:95:cc:77:71:6a:a2:82:fd:a3:eb:e2:c4:09"] # You can get this ID in the section where you registered the SSH Key
			- run:
					name: Install dependencies
					command: |
						# install the dependencies needed for your playbook
						apk add --update ansible 
			- run:
					name: Configure server
					command: |
						ansible-playbook -i inventory.txt main4.yml
					
					
workflows:
	# Name the workflow "welcome"
	my_workflow:
		# Run the welcome/run job in its own container
		jobs:
		- configure_infrastructure
